# Generated by Django 3.2.5 on 2021-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemadetails',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
