# Generated by Django 3.2.5 on 2021-08-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_schemadetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemadetails',
            name='type',
            field=models.CharField(choices=[('DF', '-----'), ('FN', 'Full name'), ('JB', 'Job'), ('EM', 'E-mail'), ('PN', 'Phone number'), ('DT', 'Date')], default='DF', max_length=2),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schema')),
            ],
        ),
    ]
