# Generated by Django 3.2.5 on 2021-08-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210804_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='schemadetails',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='schemadetails',
            name='type',
            field=models.CharField(choices=[('FN', 'Full name'), ('JB', 'Job'), ('EM', 'E-mail'), ('PN', 'Phone number'), ('DT', 'Date')], default=None, max_length=2),
        ),
    ]
